### PR TITLE
won't use codon which usage frequency below a threshold

### PR DESCRIPTION
**Pull request by Lix1993**
for codons which usage frequency below a threshold (such as 0.1),
set these usage to 0,

since `get_codons_table() `is a staticmethod ,
use `remove_codons_below_threshold()` when `codons_usage_threshold > 0`

### CODE REVIEW

**Comment by Zulko** [comment]
Thanks for the PR, I would accept it, but could you explain or give a reference explaining the need ? Is it a common thing to strictly avoid rare codons?

**Comment by Lix1993** [comment]
remove rare codons will increase proterin expression, based on our experimental results

**Comment by Zulko** [comment]
I am not against the feature, but I have two objections to the implementation:

- The current CodonOptimize methods correspond to commonly used methods well described in the literature while your need is a bit more specific to you.
- The CodonOptimize methods are more optimization objectives, and your specification would be better expressed as a hard constraint ("avoid any codon with a frequency under a certain threshold"). It would also make it faster to solve as you could restrict the mutation space to the only acceptable codons.

Therefore I would suggest, instead of adding a parameter to CodonOptimize, to create a new specification ``AvoidRareCodons(species="e_coli", min_frequency=0.20)`` that can be used in addition of CodonOptimize (or *instead* of CodonOptimize).

Would that make sense?

**Comment by Lix1993** [comment]
I think it may help.

In addition, when dealing with multiple optimization problems, `boots` cannot represent problem weights since their scores are not in same range.   
For example:  codon_usage may get a score -200 while  avoid_hairpin get a score below 10.  
Do you have any suggestion  to make optimization problem more 'equal'?

**Comment by Zulko** [comment]
Ok, I am working on the library right now so I'll add a AvoidRareCodons specification, which you'll be able to use on top of other optimization methods.

Regarding the objectives scores and weights, it is true that different optimization objectives have typical scores in different ranges, as they are not always easy to compare with one another, and there is no other way right now than to play around with the ``boost`` parameter. I recognize this is an issue and I am open to suggestions. Right now, specification scores are designed so that,  ideally, a nucleotide mutation should contribute between 0 and +1 to the overall score. However, that doesn't make every specification "comparable". Let me know if you have a particular example in mind where this could be a problem.

**Comment by Zulko** [comment]
closing this in favor of the new [AvoidRareCodons](https://github.com/Edinburgh-Genome-Foundry/DnaChisel/blob/master/dnachisel/builtin_specifications/codon_optimization/AvoidRareCodons.py) specification class.

**Comment by Lix1993** [comment]
Thanks for your help.

**Comment by Lix1993** [comment]
I haven't dealing with multi-objectives right now. But it's my purpose.

Our goal is to optimize  a cds sequence using different objectives with a uniform weight .  
We will then use experiments to determine which functions primarily affect protein expression.
Then we'll reoptimize sequence with difference weight.

I'm currently being dealing with specific features's evaluate function. Such as TAI, leading peptide...  
When hand on multi-objective problem, I'll paste an examples here.

Sorry for my poor English..

**Comment by Zulko** [comment]
No worries, it is all clear and I really appreciate your suggestions, let me know if you run into more problems or improvement ideas.

**Pull request closed without merging**
